In [2]:
import numpy as np

In [69]:
a=np.array([[1.,4.,1.],[1.,6.,-1.],[2.,-1.,2.]])
b=np.array([7.,13.,5.])
x=np.array([0,0,0])
ac=np.copy(a); bc=np.copy(b)

In [37]:
def LUdecomp(a):
    n=len(a)
    for i in range(0,n-1):
        for j in range(i+1, n):
            if a[j,i] != 0.0:
                factor = a[j,i]/a[i,i]
                a[j,i+1:n] = a[j,i+1:n] - factor*a[i,i+1:n]
                a[j,i] = factor

def LUsolve(a,b):
    n=len(a)
    x=np.zeros(n,int)
    for k in range(1,n):
        b[k] -= np.dot(a[k,0:k],b[0:k])
    x[n-1]=b[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
        x[k]=(b[k]-np.dot(a[k,k+1:n],x[k+1:n]))/a[k,k]
    return x

In [70]:
LUdecomp(a)

In [72]:
x=LUsolve(a,b)

In [73]:
x

array([ 5,  1, -2])

In [21]:
x

array([ 5.,  1., -2.])

In [74]:
np.dot(ac,x)-bc

array([ 0.,  0.,  0.])